version: "3"

services:
  db_tb:
    container_name: twitch_database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3307
    env_file:
      - docker.env.prod
    volumes:
      - ~/twitch_bot/mysql_data:/var/lib/mysql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db

  app:
    container_name: theoretically_meh
    build: .
    links:
      - 'db:database'
    depends_on:
      - 'db'
