
version: "3.8"

services:
  postgres:
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432
    env_file:
      - docker.env.prod

  pg-admin:
    image: dpage/pgadmin4
    env_file:
      - docker.env.prod
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - postgres
    links:
      - postgres:database

  application:
    depends_on:
      - postgres
    links:
      - postgres:database
    build:
      context: .
      target: build
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    command: npm run dev:run
