version: "3"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    env_file: docker.env.prod

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
