version: "3"

services:
  postgres:
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432
    env_file:
      - docker.env.prod
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4
    env_file:
      - docker.env.prod
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - postgres
    links:
      - postgres:database

  application:
    build:
      context: .
    links:
      - postgres:database
    depends_on:
      - postgres
