name: Unit Tests
run-name: Unit Tests -- ${{ github.ref }}
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      DB_TYPE: database
      DB_HOST: database
      DB_PORT: 9999
      DB_USER: database
      DB_PASS: database
      DB_BASE: database
      DB_SYNC: false
      DB_LOGG: false
      DISCORD_LINK: discord
      TWITCH_CHANNEL: twitch
      TWITCH_CLIENT: client
      TWITCH_SECRET: secret
      TWITCH_TOKEN: token
      TWITCH_USERNAME: username
      TWITCH_REQUIRED_SCOPES: scopes
      TWITCH_BROADCASTER: 1
      TWITCH_CODE: code
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test